### ISSUE TITLE
Provide ERB templates for all views

### ISSUE THREAD

**Issue by vraravam** [holyketzer/activeadmin-audit#3]

**Comment by holyketzer** [comment]
For which purpose you need erb templates? It's too expensive support more than 1 kind of same views

**Comment by vraravam** [comment]
My project still uses ERB. Either the gem should provide the default views in various templates or should provide a way for the consumer to have the views in their codebase.

**Comment by holyketzer** [comment]
Keep several kinds of templates doesn't make sense, because it's not DRY and not maintainable. 

Is there a good way to override the templates by the gem consumer: just put your templates under `views/admin/content_versions/` path, in that case you can use any template engine you like and override HTML code any way you like.
